add try catch to ensure containers are removed even if test fails

diff --git a/ci-cd/jenkins/testContainersJenkinsFile b/ci-cd/jenkins/testContainersJenkinsFile
--- a/ci-cd/jenkins/testContainersJenkinsFile
+++ b/ci-cd/jenkins/testContainersJenkinsFile
@@ -33,27 +33,44 @@ pipeline {
         stage('Run Docker Test') {
             steps {
                 script {
-                    // 1. Run all Docker containers on a shared network
-                    sh 'docker network create --driver bridge my-cotainerTest-network || true'                    
-                    sh 'docker run -d --rm --name web --network my-cotainerTest-network erezshamai707/my-web-app:latest'
-                    sh 'docker run -d --rm --name nginx --network my-cotainerTest-network -p 80:80 erezshamai707/my-nginx:latest'
-                    
-                    // 2. Wait for services to be ready
-                    echo 'Waiting 20 seconds for containers to be up and running...'
-                    sleep 20
-                    
-                    // 3. Initiate the HTTP request
-                    def response = httpRequest(url: 'http://localhost/running-containers', consoleLogResponseBody: true)
-                    
-                    // 4. Validate the JSON response
-                    def json = new groovy.json.JsonSlurper().parseText(response.content)
-                    
-                    // Check if the response is a list and contains at least one item
-                    if (json instanceof List && json.size() > 0) {
-                        echo "Response body has ${json.size()} running containers, as expected. Test passed! ✅"
-                    } else {
-                        error "Response body does not contain a list of running containers or is empty. Test failed! ❌"
-                    }
+                    def webContainerId , nginxContainerId
+                    try{
+                        // 1. Run all Docker containers on a shared network
+                        sh 'docker network create --driver bridge my-cotainerTest-network || true'  
+                        webContainerId = sh(returnStdout: true, script: "docker run -d --rm --name web --network my-cotainerTest-network erezshamai707/my-web-app:latest").trim()                  
+                        nginxContainerId = sh(returnStdout: true, script: "docker run -d --rm --name nginx --network my-cotainerTest-network -p 80:80 erezshamai707/my-nginx:latest").trim() 
+                        //sh 'docker run -d --rm --name web --network my-cotainerTest-network erezshamai707/my-web-app:latest'
+                        //sh 'docker run -d --rm --name nginx --network my-cotainerTest-network -p 80:80 erezshamai707/my-nginx:latest'
+                        
+                        // 2. Wait for services to be ready
+                        echo 'Waiting 10 seconds for containers to be up and running...'
+
+                        sleep 10
+                        
+                        // 3. Initiate the HTTP request
+                        def response = httpRequest(url: 'http://localhost/running-containers', consoleLogResponseBody: true)
+                        // Print the HTTP response content to the console
+                        echo "HTTP Response Content: ${response.content}"                        
+                        // 4. Validate the JSON response
+                        def json = new groovy.json.JsonSlurper().parseText(response.content)
+                        
+                        // Check if the response is a list and contains at least one item
+                        if (json instanceof List && json.size() > 0) {
+                            echo "Response body has ${json.size()} running containers, as expected. Test passed! ✅"
+                        } else {
+                            error "Response body does not contain a list of running containers or is empty. Test failed! ❌"
+                        }
+                    } catch (Exception e) {
+                        error "An error occurred during the test: ${e.message}"
+                    } finally {
+                        // 5. Clean up: Stop and remove containers and network
+                        if (nginxContainerId) {
+                            sh "docker stop ${nginxContainerId} || true"
+                        }
+                        if (webContainerId) {
+                            sh "docker stop ${webContainerId} || true"
+                        }
+                        //sh 'docker network rm my-cotainerTest-network || true'
                 }
             }
         }
